name: 'Mirror'

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * *"

jobs:
  mirror:
    name: Automatic Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Mirroring
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git remote add --mirror=fetch mirror "https://github.com/OCA/server-auth.git"
          git fetch mirror +refs/heads/*:refs/remotes/origin/*
          git push --force --mirror --prune origin

